version: '3.8'
services:
  db:
    image: postgres:12.4
    restart: always
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=some-user
      - POSTGRES_PASSWORD=some-pass
      - POSTGRES_DB=some_db
  php:
    build:
      ./docker/php
    volumes:
      - .:/var/www/foo:delegated
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://some-user:some-pass@db:5432/some-db?serverVersion=12.4"
      APP_ENV: "dev"
  nginx:
    image: nginx:1.18
    ports:
      - "8089:80"
    volumes:
      - .:/var/www/foo:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php